spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/usercenter

  session:
    timeout: 3600

  redis:
    host: 152.32.209.192
    port: 6379
    password: 136814
    connect-timeout: 60s
    timeout: 120s
    lettuce:
      pool:
        max-wait: 60s
        max-active: 20
        max-idle: 10
        min-idle: 5


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 0
      logic-not-delete-value: 1

server:
  port: 8080
  servlet:
    context-path: /api